import { Component, OnInit, enableProdMode } from '@angular/core';
import { Router, NavigationEnd ,Event, NavigationStart, NavigationCancel, NavigationError} from '@angular/router';
import { FormControl } from '@angular/forms';
import { environment } from '../environments/environment';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

 

export class AppComponent {
  title = 'crypto';
  nightScreen = new FormControl();
  loading = false;
  constructor(private router: Router) { 
    this.router.events.subscribe((event : Event)=>{
        switch(true){
            case event instanceof NavigationStart:{
                this.loading = true;
                break;
            }
            case event instanceof NavigationEnd:
            case event instanceof NavigationCancel:
            case event instanceof NavigationError:{
                this.loading = false;
                break;
            }
            default: {
                break;
            }
        }
    });
    
  }
  ngOnInit() {
      console.log('ngonit called twice');
      this.router.events.subscribe((evt) => {
          if (!(evt instanceof NavigationEnd)) {
              return;
          }
          window.scrollTo(0, 0)
      });
  }

  GoToTop(){
    window.scrollTo({
        top: 0,
        left: 0,
        behavior: 'smooth'
      });
  }

  NightMode(){
      environment.nightScreen = this.nightScreen.value;
  }
}

export class AppData{
    coinNameSymbolMap:Map<string,string> = new Map([
        ["BTC","Bitcoin"], ["XRP","Ripple"], ["ETH","Etherium"], ["LTC","Litecoin"], ["BCH","BitcoinCash"], ["XMR","Monero"], ["RPX","Red Pulse"], ["DBC","DeepBrain Chain"],
        ["XLM","Stellar"], ["NEO","NEO"], ["GAS","GAS"], ["OMG","OmiseGO"], ["REQ","Request Network"], ["ZRX","0x"], ["GNT","Golem"], ["BAT","Basic Attention Token"],
        ["AE","bitcoin"], ["DASH","Dash"], ["DOGE","Dogecoin"], ["SC","Siacoin"], ["TRX","Tron"], ["ETN","Electroneum"], ["ONT","Ontology"], ["ZIL","Zilliqa"],
        ["EOS","EOS"], ["POLY","Polymath"], ["DGB","DigiByte"], ["NCASH","Nucleus Vision"], ["ADA","Cardano"], ["ICX","ICON"], ["VEN","VeChain"], ["DGD","DigixDAO"],
        ["QLC","QLC Chain"], ["POWR","Power Ledger"], ["WPR","WePower"], ["WAVES","Waves"], ["WAN","Wanchain"], ["XVG","Verge"], ["BLZ","Bluzelle"], ["SUB","Substratum"],
        ["LRC","Loopring"], ["NEXO","Nexo"], ["EFX","Effect AI"], ["REP","Augur"], ["LOOM","loom Network"], ["QTUM","Qtum"], ["QKC","QuarkChain"], ["LSK","Lisk"],
        ["NPXS","PundiX"], ["USDT","Tether"], ["ETC","Etherium Classic"], ["KMD","Komodo"], ["LET","LinkEye"], ["SOUL","Phantasma"], ["PHX","Red Pulse Phoenix"], ["VET","VeChain"],
        ["BCHABC","BCH ABC"], ["BCHSV","Satoshi Vision"], ["IXT","IXT"], ["SKY","Skycoin"], ["ODE","ODEM"], ["TST","bitcoin"]
    ]);
    
    coinDtd:coinDetails = {
        networkLink:"",
        explorerlink:"string",
        symbol:"string",
        name:"Bitcoin",
        webLink:"string",
        telegramLink:"string",
        githubLink:"string",
        redditlink:"string",
        discordlink:"string",
        bitcointalklink:"string",
        whitepaperlink:"string",
        buyRating:1,
        isMinable:true,
    };

    coinNameDetailsMap:Map<string,coinDetails> = new Map([
        ["BTC",{
            networkLink:"",
            explorerlink:"https://live.blockcypher.com/btc/",
            symbol:"BTC",
            name:"Bitcoin",
            webLink:"https://bitcoin.org/",
            telegramLink:"https://t.me/bitcoinchannel",
            githubLink:"https://github.com/bitcoin/",
            redditlink:"https://www.reddit.com/r/Bitcoin/",
            discordlink:"https://discordapp.com/invite/46U2p4m",
            bitcointalklink:"https://bitcointalk.org/",
            whitepaperlink:"https://bitcoin.org/bitcoin.pdf",
            buyRating:3, isMinable:true,
        }] ,
        ["XRP",{
                networkLink:"",
                explorerlink:"https://xrpcharts.ripple.com/#/graph/",
                symbol:"XRP",
                name:"Ripple",
                webLink:"https://ripple.com/xrp/",
                telegramLink:"https://t.me/Ripple",
                githubLink:"https://github.com/ripple",
                redditlink:"https://www.reddit.com/r/Ripple/",
                discordlink:"https://discordapp.com/invite/qgfVERN",
                bitcointalklink:"string",
                whitepaperlink:"https://ripple.com/files/ripple_consensus_whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["ETH",{
                networkLink:"",
                explorerlink:"https://etherscan.io/",
                symbol:"ETH",
                name:"Etherium",
                webLink:"https://www.ethereum.org/",
                telegramLink:"https://telegram.me/ethtrader",
                githubLink:"https://github.com/ethereum",
                redditlink:"https://www.reddit.com/r/etherium/",
                discordlink:"https://discord.gg/srKTm5S",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=428589.0",
                whitepaperlink:"https://github.com/ethereum/wiki/wiki/White-Paper",
                buyRating:3, isMinable:true,
            }],
        ["LTC",{
                networkLink:"",
                explorerlink:"http://explorer.litecoin.net/chain/Litecoin",
                symbol:"LTC",
                name:"Litecoin",
                webLink:"https://litecoin.com/",
                telegramLink:"https://telegram.me/litecoin",
                githubLink:"https://github.com/litecoin-project/litecoin",
                redditlink:"https://www.reddit.com/r/litecoin/",
                discordlink:"https://discord.gg/AFkPpC2",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=47417.0",
                whitepaperlink:"https://litecoin.org/",
                buyRating:3, isMinable:true,
            }],
        ["BCH",{
                networkLink:"",
                explorerlink:"https://blockchair.com/bitcoin-cash/blocks",
                symbol:"BCH",
                name:"Bitcoin Cash",
                webLink:"https://www.bitcoincash.org/",
                telegramLink:"https://t.me/BitcoinCashFork",
                githubLink:"https://github.com/bitcoincashorg/",
                redditlink:"https://www.reddit.com/r/Bitcoincash/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2040221.0",
                whitepaperlink:"https://www.bitcoincash.org/",
                buyRating:3, isMinable:true,
            }],
        ["XMR",{
                networkLink:"",
                explorerlink:"http://moneroblocks.info/",
                symbol:"XMR",
                name:"Monero",
                webLink:"https://ww.getmonero.org/",
                telegramLink:"https://telegram.me/bitmonero",
                githubLink:"https://github.com/monero-project/monero",
                redditlink:"https://www.reddit.com/r/Monero/",
                discordlink:"https://discord.me/page/monero",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=583449.0",
                whitepaperlink:"https://github.com/monero-project/research-lab/blob/master/whitepaper/whitepaper.pdf",
                buyRating:3, isMinable:true,
            }],
        ["RPX",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/1578103c13e39df15d0d29826d957e85d770d8c9",
                symbol:"RPX",
                name:"Red Pulse",
                webLink:"https://www.redpulse.com/landing",
                telegramLink:"https://t.me/redpulse",
                githubLink:"https://coin.red-pulse.com/wp-content/uploads/redpulse-whitepaper-en.pdf",
                redditlink:"https://www.reddit.com/r/RedPulseToken/",
                discordlink:"https://www.redpulse.com/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2096780.0;all",
                whitepaperlink:"https://coin.red-pulse.com/wp-content/uploads/redpulse-whitepaper-en.pdf",
                buyRating:3, isMinable:false,
            }],
        ["DBC",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/b951ecbbc5fe37a9c280a76cb0ce0014827294cf",
                symbol:"XRP",
                name:"DeepBrain Chain",
                webLink:"https://www.deepbrainchain.org/",
                telegramLink:"http://t.me/deepbrainchain",
                githubLink:"",
                redditlink:"https://www.reddit.com/r/DeepBrainChain/",
                discordlink:"https://www.reddit.com/r/DeepBrainChain/comments/7n629p/discord_channel/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2509823.0",
                whitepaperlink:"https://dlc0uvc36o5o6.cloudfront.net/whitepapers/DeepBrainChainWhitepaper_EN.pdf",
                buyRating:3, isMinable:false,
            }],
        ["XLM",{
                networkLink:"",
                explorerlink:"https://dashboard.stellar.org/",
                symbol:"XLM",
                name:"Stellar",
                webLink:"https://www.stellar.org/",
                telegramLink:"https://t.me/StellarLumens",
                githubLink:"https://github.com/stellar",
                redditlink:"https://www.reddit.com/r/stellar",
                discordlink:"https://www.reddit.com/r/xlm/comments/7xfnii/unofficial_stellar_xlm_discord/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1428573.0",
                whitepaperlink:"https://www.stellar.org/papers/stellar-consensus-protocol.pdf",
                buyRating:3, isMinable:false,
            }],
        ["NEO",{
                networkLink:"",
                explorerlink:"https://neotracker.io/",
                symbol:"NEO",
                name:"Neo",
                webLink:"https://neo.org/",
                telegramLink:"https://telegram.me/Neo_Blockchain",
                githubLink:"https://github.com/neo-project",
                redditlink:"https://www.reddit.com/r/NEO/",
                discordlink:"https://discord.io/neo",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2057932.0",
                whitepaperlink:"http://docs.neo.org/en-us/",
                buyRating:3, isMinable:false,
            }],
        ["GAS",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
                symbol:"GAS",
                name:"Gas",
                webLink:"https://neo.org/",
                telegramLink:"https://telegram.me/Neo_Blockchain",
                githubLink:"https://github.com/neo-project",
                redditlink:"https://www.reddit.com/r/NEO/",
                discordlink:"https://discord.io/neo",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2057932.0",
                whitepaperlink:"http://docs.neo.org/en-us/",
                buyRating:3, isMinable:false,
            }],
        ["OMG",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/OmiseGo",
                symbol:"OMG",
                name:"OmiseGO ",
                webLink:"https://omg.omise.co/",
                telegramLink:"https://telegram.me/omisego",
                githubLink:"https://cdn.omise.co/omg/whitepaper.pdf",
                redditlink:"https://www.reddit.com/r/omise_go/",
                discordlink:"https://www.reddit.com/r/omise_go/comments/7sjk0g/official_telegram_group_for_omg/",
                bitcointalklink:"string",
                whitepaperlink:"https://cdn.omise.co/omg/whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["REQ",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x8f8221afbb33998d8584a2b05749ba73c37a938a",
                symbol:"REQ",
                name:"Request Network",
                webLink:"https://request.network/",
                telegramLink:"https://t.me/requestnetwork",
                githubLink:"https://github.com/RequestNetwork/",
                redditlink:"https://www.reddit.com/r/RequestNetwork/",
                discordlink:"https://discord.gg/6aGhs6v",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2137740.0",
                whitepaperlink:"https://request.network/assets/pdf/request_whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["ZRX",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/ZRX",
                symbol:"ZRX",
                name:"0x",
                webLink:"https://0xproject.com/",
                telegramLink:"https://t.me/ZRXProject",
                githubLink:"https://github.com/0xProject",
                redditlink:"https://reddit.com/r/0xproject",
                discordlink:"https://discord.gg/d3FTX3M",
                bitcointalklink:"",
                whitepaperlink:"https://0xproject.com/pdfs/0x_white_paper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["GNT",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/Golem",
                symbol:"GNT",
                name:"Golem",
                webLink:"https://golem.network/",
                telegramLink:"https://t.me/GolemProject",
                githubLink:"https://github.com/golemfactory/golem",
                redditlink:"https://www.reddit.com/r/GolemProject/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1655002.0",
                whitepaperlink:"https://golem.network/doc/Golemwhitepaper.pdf",
                buyRating:3, isMinable:true,
            }],
        ["BAT",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/Bat",
                symbol:"BAT",
                name:" Basic Attention Token",
                webLink:"https://basicattentiontoken.org/",
                telegramLink:"https://t.me/batproject",
                githubLink:"https://github.com/brave-intl/basic-attention-token-crowdsale",
                redditlink:"https://www.reddit.com/r/BATProject",
                discordlink:"https://www.reddit.com/r/BATProject/comments/79ghnv/is_there_an_existing_batbrave_discord/",
                bitcointalklink:"https://twitter.com/BAT_Community",
                whitepaperlink:"https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf",
                buyRating:3, isMinable:false,
            }],
        ["AE",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x5ca9a71b1d01849c0a95490cc00559717fcf0d1d",
                symbol:"AE",
                name:"Aeternity",
                webLink:"https://www.aeternity.com/",
                telegramLink:"https://telegram.me/aeternity",
                githubLink:"https://github.com/aeternity",
                redditlink:"https://www.reddit.com/r/Aeternity/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1733140.0",
                whitepaperlink:"https://aeternity.com/aeternity-blockchain-whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["DASH",{
                networkLink:"",
                explorerlink:"https://explorer.dash.org/",
                symbol:"DASH",
                name:"Dash",
                webLink:"https://www.dash.org/",
                telegramLink:"https://telegram.me/DashDigitalCash",
                githubLink:"https://github.com/dashpay/dash",
                redditlink:"https://www.reddit.com/r/dashpay/",
                discordlink:"https://discord.gg/9z8zX5j",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=421615.0",
                whitepaperlink:"https://github.com/dashpay/dash/wiki/Whitepaper",
                buyRating:3, isMinable:true,
            }],
        ["DOGE",{
                networkLink:"",
                explorerlink:"http://dogechain.info/chain/Dogecoin",
                symbol:"DOGE",
                name:"Dogecoin",
                webLink:"http://dogecoin.com/",
                telegramLink:"https://t.me/TheDogeHouse",
                githubLink:"https://github.com/dogecoin/dogecoin",
                redditlink:"https://www.reddit.com/r/dogecoin/",
                discordlink:"https://discord.me/page/dogecoin",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=361813.0",
                whitepaperlink:"https://github.com/dogecoin/dogecoin/blob/master/README.md",
                buyRating:3, isMinable:true,
            }],
        ["SC",{
                networkLink:"",
                explorerlink:"http://explore.sia.tech/",
                symbol:"SC",
                name:"Siacoin",
                webLink:"https://sia.tech/",
                telegramLink:"https://telegram.me/siacoin",
                githubLink:"https://github.com/NebulousLabs/Sia",
                redditlink:"https://www.reddit.com/r/siacoin/",
                discordlink:"https://discord.gg/sia",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1060294.0",
                whitepaperlink:"https://sia.tech/whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["TRX",{
                networkLink:"",
                explorerlink:"https://tronscan.org/#/",
                symbol:"TRX",
                name:"Tron",
                webLink:"https://tron.network/",
                telegramLink:"http://t.me/tronnetworkEN",
                githubLink:"https://github.com/tronprotocol",
                redditlink:"https://www.reddit.com/r/Tronix/",
                discordlink:"https://discordapp.com/invite/YJvFT3C",
                bitcointalklink:"https://medium.com/@Tronfoundation",
                whitepaperlink:"https://developers.tron.network/docs",
                buyRating:3, isMinable:false,
            }],
        ["ETN",{
                networkLink:"",
                explorerlink:"https://blockexplorer.electroneum.com/",
                symbol:"ETN",
                name:"Electroneum",
                webLink:"http://electroneum.com/",
                telegramLink:"https://t.me/joinchat/DxoSakHOdk5mqsE-LelfVg",
                githubLink:"https://github.com/electroneum",
                redditlink:"https://www.reddit.com/r/Electroneum/",
                discordlink:"https://discord.me/page/electroneum",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2353282.0",
                whitepaperlink:"http://electroneum.com/overview-white-paper.pdf",
                buyRating:3, isMinable:true,
            }],
        ["ONT",{
                networkLink:"",
                explorerlink:"https://explorer.ont.io/",
                symbol:"ONT",
                name:"Ontology",
                webLink:"https://ont.io/",
                telegramLink:"https://t.me/OntologyNetwork",
                githubLink:"https://github.com/ontio",
                redditlink:"https://www.reddit.com/r/OntologyNetwork/",
                discordlink:"https://discordapp.com/invite/4TQujHj",
                bitcointalklink:"https://medium.com/ontologynetwork",
                whitepaperlink:"https://ont.io/wp/Ontology-Introductory-White-Paper-EN.pdf",
                buyRating:3, isMinable:false,
            }],
        ["ZIL",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27",
                symbol:"ZIL",
                name:"Zilliqa",
                webLink:"https://www.zilliqa.com/",
                telegramLink:"https://t.me/zilliqachat",
                githubLink:"https://github.com/Zilliqa/Zilliqa",
                redditlink:"https://www.reddit.com/r/zilliqa/",
                discordlink:"https://twitter.com/zilliqa/status/954581826403680256?lang=en",
                bitcointalklink:"",
                whitepaperlink:"https://docs.zilliqa.com/whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["EOS",{
                networkLink:"",
                explorerlink:"https://bloks.io/",
                symbol:"EOS",
                name:"EOS",
                webLink:"https://eos.io/",
                telegramLink:"https://t.me/joinchat/AAAAAEQbOeucnaMWN0A9dQ",
                githubLink:"https://github.com/eosio",
                redditlink:"https://www.reddit.com/r/eos/",
                discordlink:"https://discord.gg/ZBABdRM",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1904415.0",
                whitepaperlink:"https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md",
                buyRating:3, isMinable:false,
            }],
        ["POLY",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec",
                symbol:"POLY",
                name:"Polymath",
                webLink:"https://www.polymath.network/",
                telegramLink:"https://t.me/PolymathNetwork",
                githubLink:"https://github.com/PolymathNetwork",
                redditlink:"https://www.reddit.com/r/PolymathNetwork/",
                discordlink:"https://discord.gg/xgCb6f6",
                bitcointalklink:"https://blog.polymath.network/",
                whitepaperlink:"https://www.polymath.network/resources/whitepaper",
                buyRating:3, isMinable:true,
            }],
        ["DGB",{
                networkLink:"",
                explorerlink:"https://digiexplorer.info/",
                symbol:"DGB",
                name:"DigiByte",
                webLink:"http://www.digibyte.io/",
                telegramLink:"https://t.me/DigiByteCoin",
                githubLink:"https://github.com/digibyte/digibyte",
                redditlink:"https://www.reddit.com/r/Digibyte/",
                discordlink:"https://discord.gg/yThZpyz",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=408268.0",
                whitepaperlink:"https://www.digibyte.io/about-digibyte-blockchain",
                buyRating:3, isMinable:true,
            }],
        ["NCASH",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x809826cceab68c387726af962713b64cb5cb3cca",
                symbol:"NCASH",
                name:"Nucleus Vision",
                webLink:"https://nucleus.vision/",
                telegramLink:"https://t.me/nucleusvision_ann",
                githubLink:"https://github.com/NucleusVision",
                redditlink:"https://www.reddit.com/r/NucleusVision/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2461585.0",
                whitepaperlink:"https://nucleus.vision/mini-whitepaper.pdf?v=1.2.9",
                buyRating:3, isMinable:false,
            }],
        ["ADA",{
                networkLink:"",
                explorerlink:"https://cardanoexplorer.com/",
                symbol:"ADA",
                name:"Cardano",
                webLink:"https://www.cardano.org/",
                telegramLink:"https://t.me/CardanoAnnouncements",
                githubLink:"https://github.com/input-output-hk/cardano-sl/",
                redditlink:"https://www.reddit.com/r/cardano/",
                discordlink:"https://www.reddit.com/r/cardano/comments/7e29rt/any_discord_channel_for_the_quicker_chat/",
                bitcointalklink:"https://cardanodocs.com/cardano/monetary-policy/",
                whitepaperlink:"https://www.cardano.org/en/academic-papers/",
                buyRating:3, isMinable:false,
            }],
        ["ICX",{
                networkLink:"",
                explorerlink:"https://tracker.icon.foundation/",
                symbol:"ICX",
                name:"ICON",
                webLink:"https://www.icon.foundation/",
                telegramLink:"https://t.me/joinchat/Fqw4igkkVmYtj--ZVi-QcA",
                githubLink:"https://github.com/icon-project",
                redditlink:"https://www.reddit.com/r/helloicon/",
                discordlink:"https://www.reddit.com/r/helloicon/comments/7mpv62/official_icon_discord_channel/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2115503.0",
                whitepaperlink:"http://docs.icon.foundation/ICON-Whitepaper-EN-Draft.pdf",
                buyRating:3, isMinable:false,
            }],
        ["VEN",{
                networkLink:"",
                explorerlink:"https://explore.veforge.com/",
                symbol:"VEN",
                name:"Vechain",
                webLink:"https://www.vechain.org/",
                telegramLink:"https://t.me/vechain_official_english",
                githubLink:"https://github.com/vechain/thor",
                redditlink:"https://www.reddit.com/r/Vechain/",
                discordlink:"https://captainaltcoin.com/how-valid-is-the-latest-criticism-of-vechain-vet/",
                bitcointalklink:"",
                whitepaperlink:"https://cdn.vechain.com/vechainthor_development_plan_and_whitepaper_en_v1.0.pdf",
                buyRating:3, isMinable:false,
            }],
        ["DGD",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/dgd",
                symbol:"DGD",
                name:"DigixDAO",
                webLink:"https://digix.global/",
                telegramLink:"https://t.me/DigixDAO",
                githubLink:"https://github.com/digixglobal",
                redditlink:"https://www.reddit.com/r/digix/",
                discordlink:"",
                bitcointalklink:"https://forum.bitcoin.com/alternative-cryptocurrencies-altcoins/digixdao-token-dgd-pre-launch-via-ccedk-acount-digixdao-t7120.html",
                whitepaperlink:"https://digix.global/whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["QLC",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/0d821bd7b6d53f5c2b40e217c6defc8bbe896cf5",
                symbol:"QLC",
                name:"QLC Chain",
                webLink:"https://qlcchain.org/",
                telegramLink:"https://t.me/joinchat/F2sRmw4x_mzgSHKhyH5AFQ",
                githubLink:"https://github.com/qlcchain/",
                redditlink:"https://www.reddit.com/r/Qlink/",
                discordlink:"https://www.reddit.com/r/Qlink/comments/8lxfd6/after_the_rebranding_we_took_some_time_to/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=3860784.0",
                whitepaperlink:"https://qlink.mobi/qlink2/res/WhitePaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["POWR",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x595832f8fc6bf59c85c527fec3740a1b7a361269",
                symbol:"POWR",
                name:"Power Ledger",
                webLink:"https://powerledger.io/",
                telegramLink:"https://t.me/joinchat/Gop-90DIMiPF7N_EtvFzjA",
                githubLink:"https://www.reddit.com/r/PowerLedger/comments/7sk2du/github_link_for_powr/",
                redditlink:"https://www.reddit.com/r/PowerLedger/",
                discordlink:"https://www.reddit.com/r/PowerLedger/comments/7fjqfp/powr_discord/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2003922.0",
                whitepaperlink:"https://powerledger.io/#papers",
                buyRating:3, isMinable:false,
            }],
        ["WPR",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x4CF488387F035FF08c371515562CBa712f9015d4",
                symbol:"WPR",
                name:"WePower",
                webLink:"https://wepower.network/",
                telegramLink:"https://t.me/WePower",
                githubLink:"https://github.com/WePowerNetwork/wepower-contracts",
                redditlink:"https://www.reddit.com/r/WePowerNetwork/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2213411.0",
                whitepaperlink:"https://whitepaperdatabase.com/wepower-wpr-whitepaper/",
                buyRating:3, isMinable:false,
            }],
        ["WAVES",{
                networkLink:"",
                explorerlink:"http://wavesexplorer.com/",
                symbol:"WAVES",
                name:"Waves",
                webLink:"https://wavesplatform.com/",
                telegramLink:"https://telegram.me/wavesnews",
                githubLink:"https://github.com/wavesplatform/",
                redditlink:"https://www.reddit.com/r/Wavesplatform/",
                discordlink:"https://twitter.com/wavesplatform/status/1041289107383758849",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=3223136.0",
                whitepaperlink:"https://blog.wavesplatform.com/waves-whitepaper-164dd6ca6a23",
                buyRating:3, isMinable:false,
            }],
        ["WAN",{
                networkLink:"",
                explorerlink:"https://explorer.wanchain.org/",
                symbol:"WAN",
                name:"Wanchain",
                webLink:"https://wanchain.org/",
                telegramLink:"https://t.me/WanchainANN",
                githubLink:"https://github.com/wanchain",
                redditlink:"https://www.reddit.com/r/wanchain/",
                discordlink:"https://www.reddit.com/r/wanchain/comments/775wp0/join_our_discord/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2110925.0",
                whitepaperlink:"https://wanchain.org/files/Wanchain-Whitepaper-EN-version.pdf",
                buyRating:3, isMinable:false,
            }],
        ["XVG",{
                networkLink:"",
                explorerlink:"https://verge-blockchain.info/",
                symbol:"XVG",
                name:"Verge",
                webLink:"http://vergecurrency.com/",
                telegramLink:"https://t.me/VERGExvg",
                githubLink:"https://github.com/vergecurrency",
                redditlink:"https://www.reddit.com/r/vergecurrency/",
                discordlink:"https://discord.gg/vergecurrency",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1365894.0",
                whitepaperlink:"https://github.com/vergecurrency/Verge-Blackpaper/blob/master/Verge-Anonymity-Centric-CryptoCurrency.pdf",
                buyRating:3, isMinable:true,
            }],
        ["BLZ",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x5732046a883704404f284ce41ffadd5b007fd668",
                symbol:"BLZ",
                name:"Bluzelle",
                webLink:"https://bluzelle.com/",
                telegramLink:"https://t.me/bluzelle",
                githubLink:"https://github.com/bluzelle/swarmDB",
                redditlink:"https://www.reddit.com/r/Bluzelle/comments/7vy1ua/bluzelle_blz_a_simple_run_down_and_analysis/",
                discordlink:"",
                bitcointalklink:"http://bitcointalk.org/index.php?topic=624778.0",
                whitepaperlink:"https://bluzelle.com/wp-content/uploads/2017/10/bluzelle-whitepaper-english1-4.pdf",
                buyRating:3, isMinable:false,
            }],
        ["SUB",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x8D75959f1E61EC2571aa72798237101F084DE63a",
                symbol:"SUB",
                name:"Substratum",
                webLink:"https://substratum.net/",
                telegramLink:"https://t.me/SubstratumCommunity",
                githubLink:"https://github.com/SubstratumNetwork/",
                redditlink:"https://www.reddit.com/r/SubstratumNetwork/",
                discordlink:"https://discord.gg/8RM7tvT",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2054963.0",
                whitepaperlink:"http://substratum.net/wp-content/uploads/2017/08/substratum_whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["LRC",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xEF68e7C694F40c8202821eDF525dE3782458639f",
                symbol:"LRC",
                name:"Loopring",
                webLink:"https://loopring.org/",
                telegramLink:"https://t.me/loopring_en",
                githubLink:"https://github.com/loopring",
                redditlink:"https://www.reddit.com/r/loopring/",
                discordlink:"https://discord.gg/KkYccYp",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2069498",
                whitepaperlink:"https://github.com/Loopring/whitepaper",
                buyRating:3, isMinable:false,
            }],
        ["NEXO",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206",
                symbol:"NEXO",
                name:"Nexo",
                webLink:"http://nexo.io/",
                telegramLink:"https://t.me/nexofinance",
                githubLink:"https://github.com/nexofinance/NEXO-Token/",
                redditlink:"https://www.reddit.com/r/Nexo/",
                discordlink:"https://discord.me/page/nexo",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=4557800.40",
                whitepaperlink:"https://nexo.io/assets/downloads/Nexo-Whitepaper.pdf?=a",
                buyRating:3, isMinable:false,
            }],
        ["EFX",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/acbc532904b6b51b5ea6d19b803d78af70e7e6f9",
                symbol:"EFX",
                name:" Effect.AI",
                webLink:"http://effect.ai/",
                telegramLink:"https://t.me/effectai",
                githubLink:"https://github.com/effectai",
                redditlink:"https://www.reddit.com/r/effectai/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2737469.0",
                whitepaperlink:"http://effect.ai/download/effect_whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["REP",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0x1985365e9f78359a9B6AD760e32412f4a445E862",
                symbol:"REP",
                name:"Augur",
                webLink:"http://www.augur.net/",
                telegramLink:"https://telegram.me/AugurProject",
                githubLink:"https://github.com/AugurProject",
                redditlink:"https://www.reddit.com/r/Augur/",
                discordlink:"https://discord.gg/faud6Fx",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=860629.0",
                whitepaperlink:"https://www.augur.net/whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["LOOM",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xa4e8c3ec456107ea67d3075bf9e3df3a75823db0",
                symbol:"LOOM",
                name:"Loom Network",
                webLink:"https://loomx.io/",
                telegramLink:"https://t.me/loomnetwork",
                githubLink:"https://github.com/loomnetwork",
                redditlink:"https://www.reddit.com/r/loomnetwork/",
                discordlink:"https://loomx.io/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=3299084.0",
                whitepaperlink:"https://medium.com/loom-network/introducing-loom-network-scaling-ethereum-today-9ea26b5b57c",
                buyRating:3, isMinable:false,
            }],
        ["QTUM",{
                networkLink:"",
                explorerlink:"https://qtum.info/",
                symbol:"QTUM",
                name:"Qtum",
                webLink:"https://qtum.org/",
                telegramLink:"https://t.me/joinchat/D5oBaw29NeOdpw6qqqf2lw",
                githubLink:"https://github.com/qtumproject/qtum/	",
                redditlink:"https://www.reddit.com/r/Qtum/",
                discordlink:"https://discordapp.com/invite/zyVMQSv",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1720632.0",
                whitepaperlink:"https://qtum.org/uploads/files/a2772efe4dc8ed1100319c6480195fb1.pdf",
                buyRating:3, isMinable:false,
            }],
        ["QKC",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xea26c4ac16d4a5a106820bc8aee85fd0b7b2b664",
                symbol:"QKC",
                name:"QuarkChain",
                webLink:"https://quarkchain.io/",
                telegramLink:"https://t.me/quarkchainio",
                githubLink:"https://github.com/QuarkChain",
                redditlink:"https://www.reddit.com/r/QuarkCoin/",
                discordlink:"https://discord.gg/kdWNmAm",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=260031.0",
                whitepaperlink:"https://quarkchain.io/QUARK%20CHAIN%20Public%20Version%200.3.5.pdf",
                buyRating:3, isMinable:false,
            }],
        ["LSK",{
                networkLink:"",
                explorerlink:"https://explorer.lisk.io/",
                symbol:"LSK",
                name:"Lisk",
                webLink:"https://lisk.io/",
                telegramLink:"https://t.me/Lisk_HQ",
                githubLink:"https://github.com/LiskHQ/",
                redditlink:"https://www.reddit.com/r/Lisk/",
                discordlink:"https://discordapp.com/invite/vSPFumK",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1346646",
                whitepaperlink:"https://lisk.io/documentation/home",
                buyRating:3, isMinable:false,
            }],
        ["NPXS",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3",
                symbol:"NPXS",
                name:"PundiX",
                webLink:"https://pundix.com/",
                telegramLink:"https://t.me/pundix",
                githubLink:"https://github.com/pundix",
                redditlink:"https://www.reddit.com/r/PundiX/",
                discordlink:"https://www.reddit.com/r/PundiX/comments/90i4wi/any_telegram_groups_that_focus_mainly_on_npxs_or/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2212228.1560",
                whitepaperlink:"https://pundix.com/pdf/PundiX_Whitepaper_EN_Ver.pdf",
                buyRating:3, isMinable:false,
            }],
        ["USDT",{
                networkLink:"",
                explorerlink:"https://www.omniexplorer.info/asset/31",
                symbol:"USDT",
                name:"Tether",
                webLink:"https://tether.to/",
                telegramLink:"https://www.reddit.com/r/btc/comments/6xvrm1/tethers_telegram_channel/",
                githubLink:"https://github.com/topics/usdt",
                redditlink:"https://www.reddit.com/r/Tether/",
                discordlink:"https://www.reddit.com/r/Tether/comments/7n5hg9/official_discord_of_tether/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=4410014.0",
                whitepaperlink:"https://tether.to/wp-content/uploads/2016/06/TetherWhitePaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["ETC",{
                networkLink:"",
                explorerlink:"http://gastracker.io/",
                symbol:"ETC",
                name:"Ethereum Classic",
                webLink:"https://ethereumclassic.org/",
                telegramLink:"https://telegram.me/ethclassic",
                githubLink:"https://github.com/ethereumproject",
                redditlink:"https://www.reddit.com/r/EthereumClassic/",
                discordlink:"https://discord.gg/HW4GckH",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1559630.0",
                whitepaperlink:"https://ethereumclassic.github.io/assets/etc-thesis.pdf",
                buyRating:3, isMinable:true,
            }],
        ["KMD",{
                networkLink:"",
                explorerlink:"https://kmdexplorer.io/",
                symbol:"KMD",
                name:" Komodo",
                webLink:"https://komodoplatform.com/",
                telegramLink:"https://telegram.me/KomodoPlatform_Official",
                githubLink:"https://github.com/KomodoPlatform",
                redditlink:"https://www.reddit.com/r/komodoplatform/",
                discordlink:"https://discord.gg/ZSrn5sJ",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1605144.0",
                whitepaperlink:"https://komodoplatform.com/whitepaper",
                buyRating:3, isMinable:true,
            }],
        ["LET",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xfa3118b34522580c35ae27f6cf52da1dbb756288",
                symbol:"LET",
                name:"LinkEye",
                webLink:"http://www.linkeye.com/",
                telegramLink:"https://t.me/linkeye_en",
                githubLink:"https://github.com/LinkEyeOfficial",
                redditlink:"https://www.reddit.com/r/LinkEye/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2437755.0",
                whitepaperlink:"https://www.linkeye.com/static/whitePaper/WhitePaperofLinkEye.pdf",
                buyRating:3, isMinable:false,
            }],
        ["SOUL",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/ed07cffad18f1308db51920d99a2af60ac66a7b3",
                symbol:"SOUL",
                name:" Phantasma",
                webLink:"https://phantasma.io/",
                telegramLink:"https://t.me/phantasma_io",
                githubLink:"https://github.com/phantasma-io",
                redditlink:"https://www.reddit.com/r/phantasma/",
                discordlink:"https://discordapp.com/invite/fkNhmmk",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=3730943.0;all",
                whitepaperlink:"https://phantasma.io/downloads/phantasma_whitepaper_en.pdf",
                buyRating:3, isMinable:false,
            }],
        ["PHX",{
                networkLink:"",
                explorerlink:"https://neotracker.io/asset/1578103c13e39df15d0d29826d957e85d770d8c9",
                symbol:"RPX",
                name:"Red Pulse",
                webLink:"https://www.redpulse.com/landing",
                telegramLink:"https://t.me/redpulse",
                githubLink:"https://coin.red-pulse.com/wp-content/uploads/redpulse-whitepaper-en.pdf",
                redditlink:"https://www.reddit.com/r/RedPulseToken/",
                discordlink:"https://www.redpulse.com/",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2096780.0;all",
                whitepaperlink:"https://coin.red-pulse.com/wp-content/uploads/redpulse-whitepaper-en.pdf",
                buyRating:3, isMinable:false,
            }],
        ["VET",{
                networkLink:"",
                explorerlink:"https://explore.veforge.com/",
                symbol:"VEN",
                name:"Vechain",
                webLink:"https://www.vechain.org/",
                telegramLink:"https://t.me/vechain_official_english",
                githubLink:"https://github.com/vechain/thor",
                redditlink:"https://www.reddit.com/r/Vechain/",
                discordlink:"https://captainaltcoin.com/how-valid-is-the-latest-criticism-of-vechain-vet/",
                bitcointalklink:"",
                whitepaperlink:"https://cdn.vechain.com/vechainthor_development_plan_and_whitepaper_en_v1.0.pdf",
                buyRating:3, isMinable:false,
            }],
        ["BCHABC",{
                networkLink:"",
                explorerlink:"https://blockchair.com/bitcoin-cash/blocks",
                symbol:"BCH",
                name:"Bitcoin Cash",
                webLink:"https://www.bitcoincash.org/",
                telegramLink:"https://t.me/BitcoinCashFork",
                githubLink:"https://github.com/bitcoincashorg/",
                redditlink:"https://www.reddit.com/r/Bitcoincash/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2040221.0",
                whitepaperlink:"https://www.bitcoincash.org/",
                buyRating:3, isMinable:true,
            }],
        ["BCHSV",{
                networkLink:"",
                explorerlink:"https://svblox.com/",
                symbol:"BCHSV",
                name:"Bitcoin SV",
                webLink:"https://bitcoinsv.io/",
                telegramLink:"",
                githubLink:"https://github.com/bitcoin-sv/bitcoin-sv",
                redditlink:"https://www.reddit.com/r/btc/comments/a6exq5/how_to_claim_the_bchsv/",
                discordlink:"",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=5079731.0;prev_next=next",
                whitepaperlink:"https://resource.bnbstatic.com/books/20181116/1542336458611.pdf",
                buyRating:3, isMinable:true,
            }],
        ["IXT",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xfca47962d45adfdfd1ab2d972315db4ce7ccf094",
                symbol:"IXT",
                name:"IXT",
                webLink:"https://www.ixt.global/",
                telegramLink:"https://t.me/iXledger",
                githubLink:"https://github.com/ixt",
                redditlink:"https://www.reddit.com/r/iXledger/",
                discordlink:"https://twitter.com/iXledger/status/922860467084824576",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=1963974.0",
                whitepaperlink:"https://www.ixledger.com/wp-content/uploads/2017/05/ixledger_whitepaper_v1.1.pdf",
                buyRating:3, isMinable:false,
            }],
        ["SKY",{
                networkLink:"",
                explorerlink:"http://explorer.skycoin.net/",
                symbol:"SKY",
                name:"Skycoin",
                webLink:"http://skycoin.net/",
                telegramLink:"https://t.me/Skycoin",
                githubLink:"https://github.com/skycoin",
                redditlink:"https://www.reddit.com/r/skycoin/",
                discordlink:"https://discord.gg/MTepVHE",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=380441.0",
                whitepaperlink:"https://downloads.skycoin.net/whitepapers/Skycoin-Whitepaper-v1.0.pdf",
                buyRating:3, isMinable:false,
            }],
        ["ODE",{
                networkLink:"",
                explorerlink:"https://etherscan.io/token/0xbf52f2ab39e26e0951d2a02b49b7702abe30406a",
                symbol:"ODE",
                name:"ODEM",
                webLink:"https://odem.io/",
                telegramLink:"https://t.me/odem_io",
                githubLink:"https://github.com/odemio/ico",
                redditlink:"https://www.reddit.com/r/ODEM/",
                discordlink:"https://odem.io/career-community-manager.php",
                bitcointalklink:"https://bitcointalk.org/index.php?topic=2591616.0",
                whitepaperlink:"https://odem.io/images/ODEM.IO-Technical-Whitepaper.pdf",
                buyRating:3, isMinable:false,
            }],
        ["TST",{
                networkLink:"",
                explorerlink:"string",
                symbol:"TST",
                name:"Ripple",
                webLink:"string",
                telegramLink:"string",
                githubLink:"string",
                redditlink:"string",
                discordlink:"string",
                bitcointalklink:"string",
                whitepaperlink:"string",
                buyRating:3, isMinable:true,
            }]



    ]);

    GetCoinName(coin:string):string{
        return this.coinNameSymbolMap.get(coin);
    }

    GetCoinDetails(coin:string):coinDetails{
     return this.coinNameDetailsMap.get(coin);
    }

   
}

export interface coinDetails{
    networkLink:string;
	explorerlink:string;
    symbol:string;
    name:string;
	webLink:string;
	telegramLink:string;
	githubLink:string;
	redditlink:string;
	discordlink:string;
	bitcointalklink:string;
    whitepaperlink:string;
    buyRating:number;
    isMinable:boolean;
}
